# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosca/ai/pending_embedding.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n bosca/ai/pending_embedding.proto\x12\x08\x62osca.ai\"@\n\x10PendingEmbedding\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x07\x63ontent\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_content\"B\n\x11PendingEmbeddings\x12-\n\tembedding\x18\x02 \x03(\x0b\x32\x1a.bosca.ai.PendingEmbeddingB\x1eZ\x1c\x62osca.io/api/protobuf/searchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosca.ai.pending_embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034bosca.io/api/protobuf/search'
  _globals['_PENDINGEMBEDDING']._serialized_start=46
  _globals['_PENDINGEMBEDDING']._serialized_end=110
  _globals['_PENDINGEMBEDDINGS']._serialized_start=112
  _globals['_PENDINGEMBEDDINGS']._serialized_end=178
# @@protoc_insertion_point(module_scope)
