# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosca/ai/vector.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62osca/ai/vector.proto\x12\x08\x62osca.ai\"\xa9\x01\n\x06Vector\x12\n\n\x02id\x18\x01 \x01(\t\x12\x30\n\x08metadata\x18\x02 \x03(\x0b\x32\x1e.bosca.ai.Vector.MetadataEntry\x12\x14\n\x07\x63ontent\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06values\x18\x04 \x03(\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\n\n\x08_content\":\n\x07Vectors\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12!\n\x07vectors\x18\x02 \x03(\x0b\x32\x10.bosca.ai.VectorB\x1eZ\x1c\x62osca.io/api/protobuf/searchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosca.ai.vector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034bosca.io/api/protobuf/search'
  _globals['_VECTOR_METADATAENTRY']._loaded_options = None
  _globals['_VECTOR_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_VECTOR']._serialized_start=36
  _globals['_VECTOR']._serialized_end=205
  _globals['_VECTOR_METADATAENTRY']._serialized_start=146
  _globals['_VECTOR_METADATAENTRY']._serialized_end=193
  _globals['_VECTORS']._serialized_start=207
  _globals['_VECTORS']._serialized_end=265
# @@protoc_insertion_point(module_scope)
