export type BookHeaderStyle = 'ide' | 'h' | 'h1' | 'h2' | 'h3' | 'toc1' | 'toc2' | 'toc3' | 'toca1' | 'toca2' | 'toca3' | 'rem' | 'usfm';
export declare const BookHeaderStyles: BookHeaderStyle[];
export type BookTitleStyle = 'mt' | 'mt1' | 'mt2' | 'mt3' | 'mt4' | 'imt' | 'imt1' | 'imt2' | 'rem';
export declare const BookTitleStyles: BookTitleStyle[];
export type BookIntroductionStyle = 'imt' | 'imt1' | 'imt2' | 'imt3' | 'imt4' | 'ib' | 'ie' | 'ili' | 'ili1' | 'ili2' | 'im' | 'imi' | 'imq' | 'io' | 'io1' | 'io2' | 'io3' | 'io4' | 'iot' | 'ip' | 'ipi' | 'ipq' | 'ipr' | 'iq' | 'iq1' | 'iq2' | 'iq3' | 'is' | 'is1' | 'is2' | 'imte' | 'imte1' | 'imte2' | 'iex' | 'rem';
export declare const BookIntroductionStyles: BookIntroductionStyle[];
export type BookIntroductionEndTitleStyle = 'mt' | 'mt1' | 'mt2' | 'mt3' | 'mt4' | 'imt' | 'imt1' | 'imt2';
export declare const BookIntroductionEndTitleStyles: BookIntroductionEndTitleStyle[];
export type BookChapterLabelStyle = 'cl';
export declare const BookChapterLabelStyles: BookChapterLabelStyle[];
export type CrossReferenceStyle = 'x' | 'ex';
export declare const CrossReferenceStyles: CrossReferenceStyle[];
export type CrossReferenceCharStyle = 'xo' | 'xop' | 'xt' | 'xta' | 'xk' | 'xq' | 'xot' | 'xnt' | 'xdc';
export declare const CrossReferenceCharStyles: CrossReferenceCharStyle[];
export type IntroCharStyle = 'ior' | 'iqt';
export declare const IntroCharStyles: IntroCharStyle[];
export type CharStyle = 'va' | 'vp' | 'ca' | 'qac' | 'qs' | 'add' | 'addpn' | 'bk' | 'dc' | 'efm' | 'fm' | 'k' | 'nd' | 'ndx' | 'ord' | 'pn' | 'png' | 'pro' | 'qt' | 'rq' | 'sig' | 'sls' | 'tl' | 'wg' | 'wh' | 'wa' | 'wj' | 'xt' | 'jmp' | 'no' | 'it' | 'bd' | 'bdit' | 'em' | 'sc' | 'sup';
export declare const CharStyles: CharStyle[];
export type FootnoteStyle = 'f' | 'fe' | 'ef';
export declare const FootnoteStyles: FootnoteStyle[];
export type FootnoteCharStyle = 'fr' | 'cat' | 'ft' | 'fk' | 'fq' | 'fqa' | 'fl' | 'fw' | 'fp' | 'fv' | 'fdc' | 'xt' | 'it' | 'bd' | 'bdit' | 'em' | 'sc';
export declare const FootnoteCharStyles: FootnoteCharStyle[];
export type FootnoteVerseStyle = 'fv';
export declare const FootnoteVerseStyles: FootnoteVerseStyle[];
export type SidebarStyle = 'esb';
export declare const SidebarStyles: SidebarStyle[];
export type ListStyle = 'lh' | 'li' | 'li1' | 'li2' | 'li3' | 'li4' | 'lf' | 'lim' | 'lim1' | 'lim2' | 'lim3' | 'lim4';
export declare const ListStyles: ListStyle[];
export type ParaStyle = 'restore' | 'cls' | 'iex' | 'ip' | 'lit' | 'm' | 'mi' | 'nb' | 'p' | 'pb' | 'pc' | 'pi' | 'pi1' | 'pi2' | 'pi3' | 'po' | 'pr' | 'pmo' | 'pm' | 'pmc' | 'pmr' | 'ph' | 'ph1' | 'ph2' | 'ph3' | 'q' | 'q1' | 'q2' | 'q3' | 'q4' | 'qa' | 'qc' | 'qr' | 'qm' | 'qm1' | 'qm2' | 'qm3' | 'qd' | 'b' | 'd' | 'ms' | 'ms1' | 'ms2' | 'ms3' | 'mr' | 'r' | 's' | 's1' | 's2' | 's3' | 's4' | 'sr' | 'sp' | 'sd' | 'sd1' | 'sd2' | 'sd3' | 'sd4' | 'ts' | 'cp' | 'cl' | 'cd' | 'mte' | 'mte1' | 'mte2' | 'p' | 'p1' | 'p2' | 'k1' | 'k2' | 'rem';
export declare const ParaStyles: ParaStyle[];
export type VerseStartStyle = 'v';
export declare const VerseStartStyles: VerseStartStyle[];
export type ListCharStyle = 'litl' | 'lik' | 'liv' | 'liv1' | 'liv2' | 'liv3' | 'liv4' | 'liv5';
export declare const ListCharStyles: ListCharStyle[];
//# sourceMappingURL=styles.d.ts.map