### Login Me - Register Action
GET http://localhost:4433/self-service/registration/api
Accept: application/json

> {% client.global.set("register_action", response.body.ui.action); %}

### Login Me - Register With Action
POST {{register_action}}
Accept: application/json
Content-Type: application/json

{
  "traits": {
    "email": "test@bosca.dev",
    "firstName": "Test",
    "lastName": "User"
  },
  "password": "vjr0awg9vdh5bth-JDW",
  "method": "password"
}

### Login Me - Get Login Action
GET http://localhost:4433/self-service/login/api
Accept: application/json

> {% client.global.set("login_action", response.body.ui.action); %}

### Login Me - Login with Action
POST {{login_action}}
Accept: application/json
Content-Type: application/json

{"identifier": "admin@bosca.dev", "password": "password", "method": "password"}

> {% client.global.set("session_token", response.body.session_token); %}

###
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer {{session_token}}

mutation {
    addMetadata(name: "hi", contentType: "text/plain", attributes: []) {
        url
        headers {
            key
            value
        }
        attributes {
            key
            value
        }
    }
}

###
POST http://localhost:5003/v1/content/collections
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "parent": "00000000-0000-0000-0000-000000000000",
  "collection": {
    "name": "test file",
    "attributes": {
      "asdf": "123"
    }
  }
}

###
POST http://localhost:5003/v1/content/metadata
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "collection": "00000000-0000-0000-0000-000000000000",
  "metadata": {
    "name": "test file",
    "contentType": "text/plain",
    "contentLength": 5,
    "attributes": {
      "asdf": "123"
    }
  }
}

> {% client.global.set("upload_url", response.body.url); client.global.set("upload_id", response.body.id); %}

###
PUT {{upload_url}}
Host: localhost:9010
Content-Type: text/plain

Hello

###
POST http://localhost:5003/v1/content/metadata/{{upload_id}}/uploaded
Authorization: Bearer {{session_token}}
Content-Type: application/json

###
GET http://localhost:8036/v1/content/metadata?id=53579709-ef96-49e4-9041-37fff9e3bcd2&id=b1c01a83-f1d0-43cf-8967-4db7ef515d35
Authorization: Bearer {{session_token}}
Content-Type: application/json

###
GET http://localhost:5003/v1/content/collections
Authorization: Bearer {{session_token}}
Content-Type: application/json


###
POST http://localhost:5003/v1/content/metadata/process
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "id": "a90e0f1b-de62-4a71-ab05-5fd95f1b55a8"
}