### Login Me - Get Login Action
GET https://accounts.bosca.io/self-service/login/api
Accept: application/json

> {% client.global.set("login_action", response.body.ui.action); %}

### Login Me - Login with Action
POST {{login_action}}
Accept: application/json
Content-Type: application/json

{"identifier": "test@bosca.dev", "password": "vjr0awg9vdh5bth-JDW", "method": "password"}

> {% client.global.set("session_token", response.body.session_token); %}

###
GRAPHQL http://localhost:8080/graphql
Authorization: Bearer {{session_token}}

mutation {
    addMetadata(name: "hi", contentType: "text/plain", attributes: []) {
        url
        headers {
            key
            value
        }
        attributes {
            key
            value
        }
    }
}


###
POST http://localhost:5003/v1/content/metadata
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "collection": "00000000-0000-0000-0000-000000000000",
  "metadata": {
    "name": "test file",
    "contentType": "text/plain",
    "attributes": {
      "asdf": "123"
    }
  }
}

> {% client.global.set("upload_url", response.body.url); %}

###
PUT {{upload_url}}
Host: localhost:9010
Content-Type: text/plain

Hello