FROM python:3.12-slim

RUN apt update && apt install -y pipx
RUN pipx install poetry

ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /app

COPY backend.llamaindex backend.llamaindex
COPY clients/python clients/python
RUN cd backend.llamaindex && poetry install --no-dev

RUN adduser --uid 1000 --shell /bin/false user
RUN echo "echo 'Starting ${BACKEND} server...' && python /app/backend.llamaindex/${BACKEND}" > /app/entrypoint

USER user

ENTRYPOINT ["sh", "/app/entrypoint"]