FROM python:3.12-slim

ARG BACKEND
ARG GRPC_PORT
ARG REST_PORT

EXPOSE $GRPC_PORT
EXPOSE $REST_PORT

RUN apt update && apt install -y pipx
RUN pipx install poetry

ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /app

COPY backend.llamaindex backend.llamaindex
COPY clients/python clients/python
RUN cd backend.llamaindex && poetry install

RUN adduser --uid 1000 --shell /bin/false user
RUN echo "echo 'Starting ${BACKEND} server...' && python /app/backend.llamaindex/${BACKEND}" > /app/entrypoint

USER user

WORKDIR /app/backend.llamaindex

ENTRYPOINT ["sh", "/app/entrypoint"]