#!/bin/sh

kubectl apply -f https://github.com/authzed/spicedb-operator/releases/latest/download/bundle.yaml

kubectl label namespace spicedb-operator linkerd.io/inject=enabled
kubectl label namespace spicedb-operator config.linkerd.io/default-inbound-policy=all-authenticated
kubectl label namespace spicedb-operator operator.1password.io/auto-restart=true

sleep 10

kubectl apply -f namespace.yaml

source ../_util/copy-database-secrets

extra="preshared_key: $(op item get --vault Services SpiceDB --format json --fields preshared_key | jq -r .value | base64)"

create_secret "spicedb" "spicedb" "spicedb" "$extra"

kubectl apply -f spicedb.yaml

export ZED_TOKEN="$(op item get --vault Services SpiceDB --format json --fields preshared_key | jq -r .value)"
cat schema | zed schema write --insecure --endpoint localhost:50052 --token $ZED_TOKEN
