#!/bin/sh

helm repo add traefik https://traefik.github.io/charts
helm repo update
helm install traefik traefik/traefik --namespace=traefik --create-namespace --values values.yaml

helm install traefik-mesh traefik/traefik-mesh --namespace=traefik-mesh --create-namespace