# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosca/search/search.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from bosca.content import metadata_pb2 as bosca_dot_content_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x62osca/search/search.proto\x12\x0c\x62osca.search\x1a\x1cgoogle/api/annotations.proto\x1a\x1c\x62osca/content/metadata.proto\"=\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\r\n\x05limit\x18\x03 \x01(\x04\";\n\x0eSearchResponse\x12)\n\x08metadata\x18\x01 \x03(\x0b\x32\x17.bosca.content.Metadata2k\n\rSearchService\x12Z\n\x06Search\x12\x1b.bosca.search.SearchRequest\x1a\x1c.bosca.search.SearchResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\"\n/v1/search:\x01*B\x1eZ\x1c\x62osca.io/api/protobuf/searchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosca.search.search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034bosca.io/api/protobuf/search'
  _globals['_SEARCHSERVICE'].methods_by_name['Search']._loaded_options = None
  _globals['_SEARCHSERVICE'].methods_by_name['Search']._serialized_options = b'\202\323\344\223\002\017\"\n/v1/search:\001*'
  _globals['_SEARCHREQUEST']._serialized_start=103
  _globals['_SEARCHREQUEST']._serialized_end=164
  _globals['_SEARCHRESPONSE']._serialized_start=166
  _globals['_SEARCHRESPONSE']._serialized_end=225
  _globals['_SEARCHSERVICE']._serialized_start=227
  _globals['_SEARCHSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
