#!/bin/sh

password="$(kubectl -n postgres get secret/postgres-pgbouncer -o jsonpath='{.data.pgbouncer-password}' | base64 -d)"

url="user=_crunchypgbouncer password=$password host=postgres-pgbouncer.postgres.svc.cluster.local dbname="

create_secret() {
name="$1"
namespace="$2"
database_name="$3"
extra_secrects="$4"
dsuri="$url$database_name"
dsuri="$(printf '%s' "$dsuri" | base64)"
kubectl apply -f - <<END
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: $name
  namespace: $namespace
data:
  datastore_uri: $dsuri
  $extra_secrects
END
}
