# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosca/jobs/jobs.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from bosca import empty_pb2 as bosca_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62osca/jobs/jobs.proto\x12\nbosca.jobs\x1a\x1cgoogle/api/annotations.proto\x1a\x11\x62osca/empty.proto\"-\n\x0bPollRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x0f\n\x07timeout\x18\x02 \x01(\x03\"+\n\x0cQueueRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x0c\n\x04json\x18\x02 \x01(\x0c\";\n\rFinishRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"\x1f\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04json\x18\x02 \x01(\x0c\"\x1b\n\rQueueResponse\x12\n\n\x02id\x18\x01 \x01(\t2\x8f\x02\n\x0bJobsService\x12V\n\x07\x45nqueue\x12\x18.bosca.jobs.QueueRequest\x1a\x19.bosca.jobs.QueueResponse\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0e/v1/jobs/queue\x12R\n\x04Poll\x12\x17.bosca.jobs.PollRequest\x1a\x0f.bosca.jobs.Job\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/jobs/queue/{queue}0\x01\x12T\n\x06\x46inish\x12\x19.bosca.jobs.FinishRequest\x1a\x0c.bosca.Empty\"!\x82\xd3\xe4\x93\x02\x1b\x1a\x16/v1/jobs/queue/{queue}:\x01*B\x1cZ\x1a\x62osca.io/api/protobuf/jobsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosca.jobs.jobs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032bosca.io/api/protobuf/jobs'
  _globals['_JOBSSERVICE'].methods_by_name['Enqueue']._loaded_options = None
  _globals['_JOBSSERVICE'].methods_by_name['Enqueue']._serialized_options = b'\202\323\344\223\002\020\"\016/v1/jobs/queue'
  _globals['_JOBSSERVICE'].methods_by_name['Poll']._loaded_options = None
  _globals['_JOBSSERVICE'].methods_by_name['Poll']._serialized_options = b'\202\323\344\223\002\030\022\026/v1/jobs/queue/{queue}'
  _globals['_JOBSSERVICE'].methods_by_name['Finish']._loaded_options = None
  _globals['_JOBSSERVICE'].methods_by_name['Finish']._serialized_options = b'\202\323\344\223\002\033\032\026/v1/jobs/queue/{queue}:\001*'
  _globals['_POLLREQUEST']._serialized_start=86
  _globals['_POLLREQUEST']._serialized_end=131
  _globals['_QUEUEREQUEST']._serialized_start=133
  _globals['_QUEUEREQUEST']._serialized_end=176
  _globals['_FINISHREQUEST']._serialized_start=178
  _globals['_FINISHREQUEST']._serialized_end=237
  _globals['_JOB']._serialized_start=239
  _globals['_JOB']._serialized_end=270
  _globals['_QUEUERESPONSE']._serialized_start=272
  _globals['_QUEUERESPONSE']._serialized_end=299
  _globals['_JOBSSERVICE']._serialized_start=302
  _globals['_JOBSSERVICE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
