# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bosca import empty_pb2 as bosca_dot_empty__pb2
from bosca.jobs import jobs_pb2 as bosca_dot_jobs_dot_jobs__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bosca/jobs/jobs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class JobsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/bosca.jobs.JobsService/Enqueue',
                request_serializer=bosca_dot_jobs_dot_jobs__pb2.QueueRequest.SerializeToString,
                response_deserializer=bosca_dot_jobs_dot_jobs__pb2.QueueResponse.FromString,
                _registered_method=True)
        self.Poll = channel.unary_stream(
                '/bosca.jobs.JobsService/Poll',
                request_serializer=bosca_dot_jobs_dot_jobs__pb2.PollRequest.SerializeToString,
                response_deserializer=bosca_dot_jobs_dot_jobs__pb2.Job.FromString,
                _registered_method=True)
        self.Finish = channel.unary_unary(
                '/bosca.jobs.JobsService/Finish',
                request_serializer=bosca_dot_jobs_dot_jobs__pb2.FinishRequest.SerializeToString,
                response_deserializer=bosca_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class JobsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Enqueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Poll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=bosca_dot_jobs_dot_jobs__pb2.QueueRequest.FromString,
                    response_serializer=bosca_dot_jobs_dot_jobs__pb2.QueueResponse.SerializeToString,
            ),
            'Poll': grpc.unary_stream_rpc_method_handler(
                    servicer.Poll,
                    request_deserializer=bosca_dot_jobs_dot_jobs__pb2.PollRequest.FromString,
                    response_serializer=bosca_dot_jobs_dot_jobs__pb2.Job.SerializeToString,
            ),
            'Finish': grpc.unary_unary_rpc_method_handler(
                    servicer.Finish,
                    request_deserializer=bosca_dot_jobs_dot_jobs__pb2.FinishRequest.FromString,
                    response_serializer=bosca_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bosca.jobs.JobsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bosca.jobs.JobsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bosca.jobs.JobsService/Enqueue',
            bosca_dot_jobs_dot_jobs__pb2.QueueRequest.SerializeToString,
            bosca_dot_jobs_dot_jobs__pb2.QueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Poll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bosca.jobs.JobsService/Poll',
            bosca_dot_jobs_dot_jobs__pb2.PollRequest.SerializeToString,
            bosca_dot_jobs_dot_jobs__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bosca.jobs.JobsService/Finish',
            bosca_dot_jobs_dot_jobs__pb2.FinishRequest.SerializeToString,
            bosca_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
