FROM alpine:3.19.1

RUN curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh
ENV PATH $PATH:$HOME/.goose/bin

WORKDIR /app/scripts
COPY scripts .

WORKDIR /app
COPY database .

CMD ["/app/scripts/database-migrate"]