#!/bin/sh

set -e

curl \
  -X POST 'http://localhost:7700/keys' \
  -H 'Authorization: Bearer p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "description": "Manage",
    "actions": ["*"],
    "indexes": ["*"],
    "expiresAt": null
  }'

curl \
  -X POST 'http://localhost:7700/keys' \
  -H 'Authorization: Bearer p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "description": "Search",
    "actions": ["search"],
    "indexes": ["*"],
    "expiresAt": null
  }'

curl \
  -X GET 'http://localhost:7700/keys' \
  -H 'Authorization: Bearer p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M' \
  -H 'Accept: application/json' | jq

curl \
  -X POST 'http://localhost:7700/indexes' \
  -H 'Authorization: Bearer p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "uid": "metadata",
    "primaryKey": "id"
  }'

curl \
  -X PATCH 'http://localhost:7700/experimental-features/' \
  -H 'Authorization: Bearer p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M' \
  -H 'Content-Type: application/json'  \
  --data-binary '{
    "vectorStore": true
  }'

curl \
  -X PATCH 'http://localhost:7700/indexes/metadata/settings' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M' \
  --data-binary '{
    "embedders": {
      "default": {
        "source": "huggingFace",
        "model": "BAAI/bge-base-en-v1.5",
        "documentTemplate": "A document named '{{doc.name}}' with the body of {{doc.body}}"
      }
    }
  }'
