//
// Copyright 2024 Sowers, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file bosca/profiles/profiles.proto (package bosca.profiles, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty } from "../empty_pb";
import { Profile, ProfileAttributeTypes, ProfileConfiguration } from "./profiles_pb";
import { MethodKind } from "@bufbuild/protobuf";
import { IdsRequest } from "../requests_pb";

/**
 * @generated from service bosca.profiles.ProfilesService
 */
export const ProfilesService = {
  typeName: "bosca.profiles.ProfilesService",
  methods: {
    /**
     * @generated from rpc bosca.profiles.ProfilesService.GetConfiguration
     */
    getConfiguration: {
      name: "GetConfiguration",
      I: Empty,
      O: ProfileConfiguration,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bosca.profiles.ProfilesService.GetMyProfile
     */
    getMyProfile: {
      name: "GetMyProfile",
      I: Empty,
      O: Profile,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bosca.profiles.ProfilesService.GetProfileAttributeTypes
     */
    getProfileAttributeTypes: {
      name: "GetProfileAttributeTypes",
      I: IdsRequest,
      O: ProfileAttributeTypes,
      kind: MethodKind.Unary,
    },
  }
} as const;

