FROM golang:1.22.3-bookworm

RUN apt update && apt install -y curl ca-certificates gpg
RUN curl https://pkg.authzed.com/apt/gpg.key | apt-key add -
RUN sh -c 'echo "deb https://pkg.authzed.com/apt/ * *" > /etc/apt/sources.list.d/authzed.list'
RUN apt update
RUN apt install -y zed jq
RUN curl https://raw.githubusercontent.com/ory/meta/master/install.sh > install.sh
RUN sh install.sh -d -b . kratos v1.1.0
RUN mv ./kratos /usr/local/bin/

ENV PATH="/usr/local/bin:${PATH}"

WORKDIR /app

COPY ./spicedb/initialize .
COPY ./spicedb/schema .
COPY ./spicedb/administrator.json .
RUN chmod +x initialize

CMD ["./initialize"]