#!/bin/sh

set -e

echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin

echo "Publishing Docker Images...."

docker image push --all-tags ghcr.io/sowers-io/bosca/bosca-ui

echo "...done"