//
// Copyright 2024 Sowers, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: bosca/content/storage_systems.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageSystemType int32

const (
	StorageSystemType_unknown_storage_system       StorageSystemType = 0
	StorageSystemType_vector_storage_system        StorageSystemType = 1
	StorageSystemType_search_storage_system        StorageSystemType = 2
	StorageSystemType_metadata_storage_system      StorageSystemType = 3
	StorageSystemType_supplementary_storage_system StorageSystemType = 4
)

// Enum value maps for StorageSystemType.
var (
	StorageSystemType_name = map[int32]string{
		0: "unknown_storage_system",
		1: "vector_storage_system",
		2: "search_storage_system",
		3: "metadata_storage_system",
		4: "supplementary_storage_system",
	}
	StorageSystemType_value = map[string]int32{
		"unknown_storage_system":       0,
		"vector_storage_system":        1,
		"search_storage_system":        2,
		"metadata_storage_system":      3,
		"supplementary_storage_system": 4,
	}
)

func (x StorageSystemType) Enum() *StorageSystemType {
	p := new(StorageSystemType)
	*p = x
	return p
}

func (x StorageSystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageSystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_bosca_content_storage_systems_proto_enumTypes[0].Descriptor()
}

func (StorageSystemType) Type() protoreflect.EnumType {
	return &file_bosca_content_storage_systems_proto_enumTypes[0]
}

func (x StorageSystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageSystemType.Descriptor instead.
func (StorageSystemType) EnumDescriptor() ([]byte, []int) {
	return file_bosca_content_storage_systems_proto_rawDescGZIP(), []int{0}
}

type StorageSystem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          StorageSystemType `protobuf:"varint,2,opt,name=type,proto3,enum=bosca.content.StorageSystemType" json:"type,omitempty"`
	Name          string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string            `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Configuration map[string]string `protobuf:"bytes,5,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StorageSystem) Reset() {
	*x = StorageSystem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosca_content_storage_systems_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSystem) ProtoMessage() {}

func (x *StorageSystem) ProtoReflect() protoreflect.Message {
	mi := &file_bosca_content_storage_systems_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSystem.ProtoReflect.Descriptor instead.
func (*StorageSystem) Descriptor() ([]byte, []int) {
	return file_bosca_content_storage_systems_proto_rawDescGZIP(), []int{0}
}

func (x *StorageSystem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StorageSystem) GetType() StorageSystemType {
	if x != nil {
		return x.Type
	}
	return StorageSystemType_unknown_storage_system
}

func (x *StorageSystem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageSystem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StorageSystem) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type StorageSystems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Systems []*StorageSystem `protobuf:"bytes,1,rep,name=systems,proto3" json:"systems,omitempty"`
}

func (x *StorageSystems) Reset() {
	*x = StorageSystems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosca_content_storage_systems_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageSystems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSystems) ProtoMessage() {}

func (x *StorageSystems) ProtoReflect() protoreflect.Message {
	mi := &file_bosca_content_storage_systems_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSystems.ProtoReflect.Descriptor instead.
func (*StorageSystems) Descriptor() ([]byte, []int) {
	return file_bosca_content_storage_systems_proto_rawDescGZIP(), []int{1}
}

func (x *StorageSystems) GetSystems() []*StorageSystem {
	if x != nil {
		return x.Systems
	}
	return nil
}

type StorageSystemModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Type  string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *StorageSystemModel) Reset() {
	*x = StorageSystemModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosca_content_storage_systems_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageSystemModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSystemModel) ProtoMessage() {}

func (x *StorageSystemModel) ProtoReflect() protoreflect.Message {
	mi := &file_bosca_content_storage_systems_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSystemModel.ProtoReflect.Descriptor instead.
func (*StorageSystemModel) Descriptor() ([]byte, []int) {
	return file_bosca_content_storage_systems_proto_rawDescGZIP(), []int{2}
}

func (x *StorageSystemModel) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *StorageSystemModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type StorageSystemModels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models []*StorageSystemModel `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
}

func (x *StorageSystemModels) Reset() {
	*x = StorageSystemModels{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosca_content_storage_systems_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageSystemModels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSystemModels) ProtoMessage() {}

func (x *StorageSystemModels) ProtoReflect() protoreflect.Message {
	mi := &file_bosca_content_storage_systems_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSystemModels.ProtoReflect.Descriptor instead.
func (*StorageSystemModels) Descriptor() ([]byte, []int) {
	return file_bosca_content_storage_systems_proto_rawDescGZIP(), []int{3}
}

func (x *StorageSystemModels) GetModels() []*StorageSystemModel {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_bosca_content_storage_systems_proto protoreflect.FileDescriptor

var file_bosca_content_storage_systems_proto_rawDesc = []byte{
	0x0a, 0x23, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x1a, 0x19, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa4, 0x02, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x20, 0x2e, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x55, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x40, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x48, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x36, 0x0a, 0x07, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6f, 0x73, 0x63,
	0x61, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x54, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x50, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x39, 0x0a,
	0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x62, 0x6f, 0x73, 0x63, 0x61, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2a, 0xa4, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x16, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x02,
	0x12, 0x1b, 0x0a, 0x17, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x03, 0x12, 0x20, 0x0a,
	0x1c, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x04, 0x42,
	0x25, 0x5a, 0x23, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bosca_content_storage_systems_proto_rawDescOnce sync.Once
	file_bosca_content_storage_systems_proto_rawDescData = file_bosca_content_storage_systems_proto_rawDesc
)

func file_bosca_content_storage_systems_proto_rawDescGZIP() []byte {
	file_bosca_content_storage_systems_proto_rawDescOnce.Do(func() {
		file_bosca_content_storage_systems_proto_rawDescData = protoimpl.X.CompressGZIP(file_bosca_content_storage_systems_proto_rawDescData)
	})
	return file_bosca_content_storage_systems_proto_rawDescData
}

var file_bosca_content_storage_systems_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bosca_content_storage_systems_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bosca_content_storage_systems_proto_goTypes = []any{
	(StorageSystemType)(0),      // 0: bosca.content.StorageSystemType
	(*StorageSystem)(nil),       // 1: bosca.content.StorageSystem
	(*StorageSystems)(nil),      // 2: bosca.content.StorageSystems
	(*StorageSystemModel)(nil),  // 3: bosca.content.StorageSystemModel
	(*StorageSystemModels)(nil), // 4: bosca.content.StorageSystemModels
	nil,                         // 5: bosca.content.StorageSystem.ConfigurationEntry
	(*Model)(nil),               // 6: bosca.content.Model
}
var file_bosca_content_storage_systems_proto_depIdxs = []int32{
	0, // 0: bosca.content.StorageSystem.type:type_name -> bosca.content.StorageSystemType
	5, // 1: bosca.content.StorageSystem.configuration:type_name -> bosca.content.StorageSystem.ConfigurationEntry
	1, // 2: bosca.content.StorageSystems.systems:type_name -> bosca.content.StorageSystem
	6, // 3: bosca.content.StorageSystemModel.model:type_name -> bosca.content.Model
	3, // 4: bosca.content.StorageSystemModels.models:type_name -> bosca.content.StorageSystemModel
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bosca_content_storage_systems_proto_init() }
func file_bosca_content_storage_systems_proto_init() {
	if File_bosca_content_storage_systems_proto != nil {
		return
	}
	file_bosca_content_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bosca_content_storage_systems_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StorageSystem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosca_content_storage_systems_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StorageSystems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosca_content_storage_systems_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StorageSystemModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosca_content_storage_systems_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StorageSystemModels); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bosca_content_storage_systems_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bosca_content_storage_systems_proto_goTypes,
		DependencyIndexes: file_bosca_content_storage_systems_proto_depIdxs,
		EnumInfos:         file_bosca_content_storage_systems_proto_enumTypes,
		MessageInfos:      file_bosca_content_storage_systems_proto_msgTypes,
	}.Build()
	File_bosca_content_storage_systems_proto = out.File
	file_bosca_content_storage_systems_proto_rawDesc = nil
	file_bosca_content_storage_systems_proto_goTypes = nil
	file_bosca_content_storage_systems_proto_depIdxs = nil
}
