//
// Copyright 2024 Sowers, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: bosca/content/workflows.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetWorkflowStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetadataId string `protobuf:"bytes,1,opt,name=metadata_id,json=metadataId,proto3" json:"metadata_id,omitempty"`
	StateId    string `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	Status     string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Immediate  bool   `protobuf:"varint,4,opt,name=immediate,proto3" json:"immediate,omitempty"`
}

func (x *SetWorkflowStateRequest) Reset() {
	*x = SetWorkflowStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosca_content_workflows_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWorkflowStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkflowStateRequest) ProtoMessage() {}

func (x *SetWorkflowStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bosca_content_workflows_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkflowStateRequest.ProtoReflect.Descriptor instead.
func (*SetWorkflowStateRequest) Descriptor() ([]byte, []int) {
	return file_bosca_content_workflows_proto_rawDescGZIP(), []int{0}
}

func (x *SetWorkflowStateRequest) GetMetadataId() string {
	if x != nil {
		return x.MetadataId
	}
	return ""
}

func (x *SetWorkflowStateRequest) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *SetWorkflowStateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SetWorkflowStateRequest) GetImmediate() bool {
	if x != nil {
		return x.Immediate
	}
	return false
}

type SetWorkflowStateCompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetadataId string `protobuf:"bytes,1,opt,name=metadata_id,json=metadataId,proto3" json:"metadata_id,omitempty"`
	Status     string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetWorkflowStateCompleteRequest) Reset() {
	*x = SetWorkflowStateCompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bosca_content_workflows_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWorkflowStateCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkflowStateCompleteRequest) ProtoMessage() {}

func (x *SetWorkflowStateCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bosca_content_workflows_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkflowStateCompleteRequest.ProtoReflect.Descriptor instead.
func (*SetWorkflowStateCompleteRequest) Descriptor() ([]byte, []int) {
	return file_bosca_content_workflows_proto_rawDescGZIP(), []int{1}
}

func (x *SetWorkflowStateCompleteRequest) GetMetadataId() string {
	if x != nil {
		return x.MetadataId
	}
	return ""
}

func (x *SetWorkflowStateCompleteRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_bosca_content_workflows_proto protoreflect.FileDescriptor

var file_bosca_content_workflows_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2f,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x8b,
	0x01, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x6d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x69, 0x6d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x22, 0x5a, 0x0a, 0x1f,
	0x53, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x25, 0x5a, 0x23, 0x62, 0x6f, 0x73, 0x63,
	0x61, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x62, 0x6f, 0x73, 0x63, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bosca_content_workflows_proto_rawDescOnce sync.Once
	file_bosca_content_workflows_proto_rawDescData = file_bosca_content_workflows_proto_rawDesc
)

func file_bosca_content_workflows_proto_rawDescGZIP() []byte {
	file_bosca_content_workflows_proto_rawDescOnce.Do(func() {
		file_bosca_content_workflows_proto_rawDescData = protoimpl.X.CompressGZIP(file_bosca_content_workflows_proto_rawDescData)
	})
	return file_bosca_content_workflows_proto_rawDescData
}

var file_bosca_content_workflows_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bosca_content_workflows_proto_goTypes = []any{
	(*SetWorkflowStateRequest)(nil),         // 0: bosca.content.SetWorkflowStateRequest
	(*SetWorkflowStateCompleteRequest)(nil), // 1: bosca.content.SetWorkflowStateCompleteRequest
}
var file_bosca_content_workflows_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bosca_content_workflows_proto_init() }
func file_bosca_content_workflows_proto_init() {
	if File_bosca_content_workflows_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bosca_content_workflows_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SetWorkflowStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bosca_content_workflows_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SetWorkflowStateCompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bosca_content_workflows_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bosca_content_workflows_proto_goTypes,
		DependencyIndexes: file_bosca_content_workflows_proto_depIdxs,
		MessageInfos:      file_bosca_content_workflows_proto_msgTypes,
	}.Build()
	File_bosca_content_workflows_proto = out.File
	file_bosca_content_workflows_proto_rawDesc = nil
	file_bosca_content_workflows_proto_goTypes = nil
	file_bosca_content_workflows_proto_depIdxs = nil
}
