#!/bin/sh

# Copyright 2024 Sowers, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

echo "Building Docker Images...."

ROOT=`pwd`

tag="latest"

if [ "$IMAGE_TAG" != "" ]; then
  tag="$IMAGE_TAG"
fi

build_app() {
    app=$1

    echo "Building $app...\n"

    docker build --build-arg="BACKEND=$app" -t ghcr.io/sowers-io/bosca/$app:latest .
    docker image tag ghcr.io/sowers-io/bosca/$app:latest ghcr.io/sowers-io/bosca/$app:$tag
}

build_migrations() {
  app=$1

  if [ -d "$ROOT/database/$app" ]; then
    echo "Building $app migration...\n"

    docker build --build-arg="BACKEND=$app" -f Dockerfile-migration -t ghcr.io/sowers-io/bosca/$app-migrations:latest .
    docker image tag ghcr.io/sowers-io/bosca/$app-migrations:latest ghcr.io/sowers-io/bosca/$app-migrations:$tag
  else
    echo "No migrations found for $ROOT/database/$app"
  fi
}

while IFS= read -r app
do
  build_app "$app"
  build_migrations "$app"
done < "$ROOT/scripts/apps"


echo "...done"