#!/bin/sh

# Copyright 2024 Sowers, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Building Docker Images...."

ROOT=`pwd`

tag="latest"

if [ "$IMAGE_TAG" != "" ]; then
  tag="$IMAGE_TAG"
fi

build_app() {
    app=$1

    echo "Building $app...\n"

    cd $ROOT/build/$app
    cp $ROOT/docker/Dockerfile-go Dockerfile
    docker build -t ghcr.io/sowers-io/bosca/$app:$tag .
    cd $ROOT
}

build_migrations() {
  mkdir -p $ROOT/build/migrations
  cd $ROOT/build/migrations
  mkdir -p scripts
  cd scripts
  cp $ROOT/scripts/apps .
  cp $ROOT/scripts/database-migrate .
  cd ..
  cp -Rf $ROOT/database .
  cp $ROOT/docker/Dockerfile-migration Dockerfile
  docker build -t ghcr.io/sowers-io/bosca/migrations:$tag .
}

while IFS= read -r app
do
  build_app "$app"
done < "$ROOT/scripts/apps"

build_migrations

echo "...done"