#!/bin/sh

set -e

if [ "$IMAGE_TAG" = "" ]; then
  IMAGE_TAG="latest"
fi

for project in content graphql uploads workflow workflow-queue workflow-workers workflow-dashboard ui; do
  if [ "$1" = "publish" ]; then
    docker push ghcr.io/sowers-io/bosca/$project:$IMAGE_TAG
  else
    docker build . --target $project --tag ghcr.io/sowers-io/bosca/$project:$IMAGE_TAG
  fi
done

for migration in content profiles security; do
  if [ "$1" = "publish" ]; then
    docker push ghcr.io/sowers-io/bosca/migration-$migration:$IMAGE_TAG
  else
    docker build . -f Dockerfile-migration --build-arg BACKEND=$migration --tag ghcr.io/sowers-io/bosca/migration-$migration:$IMAGE_TAG
  fi
done