#!/bin/sh

# Copyright 2024 Sowers, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

echo "Migrating Database...."

ROOT=`pwd`

migrate() {
  DIR="$ROOT/database/$1"
  if [ -d "$DIR" ]; then
    echo "Migrating $app...\n"

    cd $DIR
    goose postgres "$2" up
  fi
}

while IFS= read -r app
do
  VAR_NAME="${app}_CONNECTION_STRING"
  CONNECTION_STRING=$(eval echo "$"$VAR_NAME)

  migrate "$app" "$CONNECTION_STRING"
done < "$ROOT/scripts/apps"

echo "...done"