#!/bin/sh

# Copyright 2024 Sowers, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

mkdir -p ~/.kube
chmod go-rwx ~/.kube

echo $KUBE_CONFIG | base64 -d > ~/.kube/config
chown $(id -u):$(id -g) ~/.kube/config

cd kubernetes

echo $DOCKER_CONFIG_JSON > .dockerconfigjson

sed -i.back "s/latest/$IMAGE_TAG/g" kustomization.yaml

kubectl kustomize | kubectl apply -f -
kubectl kustomize | kubectl rollout status -f -