#!/bin/sh

set -e

ROOT=`pwd`
OUTDIR="$ROOT/backend/api/protobuf"
TSOUTDIR="$ROOT/build/ts/api/protobuf"

protoc -I $ROOT/protobuf --go_out=$OUTDIR --go_opt=paths=source_relative \
  --go-grpc_out=$OUTDIR --go-grpc_opt=paths=source_relative \
  --grpc-gateway_out=$OUTDIR --grpc-gateway_opt=paths=source_relative \
  $ROOT/protobuf/profiles/*.proto \
  $ROOT/protobuf/content/*.proto \
  $ROOT/protobuf/security/*.proto \
  $ROOT/protobuf/*.proto

mkdir -p build/ts/api/protobuf
npm --prefix build install protoc-gen-ts grpc-tools @grpc/grpc-js google-protobuf

protoc -I $ROOT/protobuf \
  --grpc_out=grpc_ts:$TSOUTDIR \
  --ts_out=grpc_ts:$TSOUTDIR \
  --plugin=protoc-gen-grpc=$ROOT/build/node_modules/.bin/grpc_tools_node_protoc_plugin \
  --plugin=protoc-gen-ts=$ROOT/build/node_modules/.bin/protoc-gen-ts \
  $ROOT/protobuf/profiles/*.proto \
  $ROOT/protobuf/content/*.proto \
  $ROOT/protobuf/security/*.proto \
  $ROOT/protobuf/*.proto