#!/bin/sh

set -e

ROOT=`pwd`
OUTDIR="$ROOT/api/api/protobuf"

protoc -I $ROOT/protobuf --go_out=$OUTDIR --go_opt=paths=source_relative \
  --go-grpc_out=$OUTDIR --go-grpc_opt=paths=source_relative \
  --grpc-gateway_out=$OUTDIR --grpc-gateway_opt=paths=source_relative \
  $ROOT/protobuf/accounts/accounts.proto \
  $ROOT/protobuf/profiles/profiles.proto \
  $ROOT/protobuf/content/content.proto \
  $ROOT/protobuf/empty.proto \
  $ROOT/protobuf/requests.proto