#!/bin/sh

set -e

./scripts/initialize

cd services
docker-compose up -d
cd ..

echo "...... Waiting for docker to settle ......."
sleep 5
echo "...... Continuing ......."

./scripts/initialize-database-dev
./scripts/initialize-minio-dev
./services/meilisearch/initialize

echo "\n########## Development Environment is Running ############"