#!/bin/sh

# Copyright 2024 Sowers, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ "$OSTYPE" = "darwin23" ]; then
  brew install minio/stable/mc
  brew install authzed/tap/zed
else
  sudo apt update && sudo apt install -y curl ca-certificates gpg
  curl https://apt.fury.io/authzed/gpg.key | sudo apt-key add -
  sudo sh -c 'echo "deb https://apt.fury.io/authzed/ * *" > /etc/apt/sources.list.d/fury.list'
  sudo apt update && sudo apt install -y zed

  mkdir -p $HOME/bin
  curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/bin/mc

  chmod +x $HOME/bin/mc
  export PATH=$PATH:$HOME/bin/mc
fi

go install github.com/pressly/goose/v3/cmd/goose@latest
go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
go install github.com/boumenot/gocover-cobertura@latest

go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

cd backend; go mod download