#!/bin/sh

if [ "$OSTYPE" = "darwin23" ]; then
  brew install goose
else
  curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh
  export PATH="$PATH:$HOME/.goose/bin"
fi

GOOSE_DRIVER=postgres
GOOSE_DBSTRING="$CONNECTION_STRING"
GOOSE_MIGRATION_DIR="database/$2"

cd database/content
goose up