#!/bin/sh

# Copyright 2024 Sowers, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin

echo "Publishing Docker Images...."

ROOT=`pwd`

tag="latest"

if [ "$IMAGE_TAG" != "" ]; then
  tag="$IMAGE_TAG"
fi

build() {
    app=$1
    docker image push -t ghcr.io/sowers-io/bosca/$app:$tag .
}

while IFS= read -r app
do
  build "$app"
done < "$ROOT/scripts/apps"

echo "...done"