#!/bin/sh

helm repo add kong https://charts.konghq.com
helm repo update

helm install kgo kong/gateway-operator -n kong-system --create-namespace --values values.yaml

kubectl create namespace kong

kubectl apply -f gateway-class.yaml