# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosca/content/collections.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosca.content import metadata_pb2 as bosca_dot_content_dot_metadata__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62osca/content/collections.proto\x12\rbosca.content\x1a\x1c\x62osca/content/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n\x14\x41\x64\x64\x43ollectionRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\x12-\n\ncollection\x18\x02 \x01(\x0b\x32\x19.bosca.content.Collection\"x\n\x18\x41\x64\x64\x43ollectionItemRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x1d\n\x13\x63hild_collection_id\x18\x02 \x01(\tH\x00\x12\x1b\n\x11\x63hild_metadata_id\x18\x03 \x01(\tH\x00\x42\t\n\x07item_id\"\xc4\x02\n\nCollection\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12+\n\x04type\x18\x05 \x01(\x0e\x32\x1d.bosca.content.CollectionType\x12\x14\n\x0c\x63\x61tegory_ids\x18\x0c \x03(\t\x12\x0c\n\x04tags\x18\r \x03(\t\x12=\n\nattributes\x18\x0e \x03(\x0b\x32).bosca.content.Collection.AttributesEntry\x12+\n\x07\x63reated\x18\x14 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08modified\x18\x15 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"?\n\x0f\x43ollectionItems\x12,\n\x05items\x18\x01 \x03(\x0b\x32\x1d.bosca.content.CollectionItem\"v\n\x0e\x43ollectionItem\x12+\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.bosca.content.MetadataH\x00\x12/\n\ncollection\x18\x03 \x01(\x0b\x32\x19.bosca.content.CollectionH\x00\x42\x06\n\x04Item*4\n\x0e\x43ollectionType\x12\x0c\n\x08standard\x10\x00\x12\n\n\x06\x66older\x10\x01\x12\x08\n\x04root\x10\x02\x42%Z#bosca.io/api/protobuf/bosca/contentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosca.content.collections_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#bosca.io/api/protobuf/bosca/content'
  _globals['_COLLECTION_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_COLLECTION_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_COLLECTIONTYPE']._serialized_start=834
  _globals['_COLLECTIONTYPE']._serialized_end=886
  _globals['_ADDCOLLECTIONREQUEST']._serialized_start=113
  _globals['_ADDCOLLECTIONREQUEST']._serialized_end=198
  _globals['_ADDCOLLECTIONITEMREQUEST']._serialized_start=200
  _globals['_ADDCOLLECTIONITEMREQUEST']._serialized_end=320
  _globals['_COLLECTION']._serialized_start=323
  _globals['_COLLECTION']._serialized_end=647
  _globals['_COLLECTION_ATTRIBUTESENTRY']._serialized_start=598
  _globals['_COLLECTION_ATTRIBUTESENTRY']._serialized_end=647
  _globals['_COLLECTIONITEMS']._serialized_start=649
  _globals['_COLLECTIONITEMS']._serialized_end=712
  _globals['_COLLECTIONITEM']._serialized_start=714
  _globals['_COLLECTIONITEM']._serialized_end=832
# @@protoc_insertion_point(module_scope)
