# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosca/content/permissions.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62osca/content/permissions.proto\x12\rbosca.content\"\xe0\x01\n\x16PermissionCheckRequest\x12\x0e\n\x06object\x18\x01 \x01(\t\x12\x38\n\x0bobject_type\x18\x02 \x01(\x0e\x32#.bosca.content.PermissionObjectType\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12:\n\x0csubject_type\x18\x04 \x01(\x0e\x32$.bosca.content.PermissionSubjectType\x12/\n\x06\x61\x63tion\x18\x05 \x01(\x0e\x32\x1f.bosca.content.PermissionAction\"*\n\x17PermissionCheckResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\"I\n\x0bPermissions\x12\n\n\x02id\x18\x01 \x01(\t\x12.\n\x0bpermissions\x18\x02 \x03(\x0b\x32\x19.bosca.content.Permission\"\x9a\x01\n\nPermission\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12:\n\x0csubject_type\x18\x03 \x01(\x0e\x32$.bosca.content.PermissionSubjectType\x12\x33\n\x08relation\x18\x05 \x01(\x0e\x32!.bosca.content.PermissionRelation*n\n\x12PermissionRelation\x12\x0b\n\x07viewers\x10\x00\x12\x0f\n\x0b\x64iscoverers\x10\x01\x12\x0b\n\x07\x65\x64itors\x10\x02\x12\x0c\n\x08managers\x10\x03\x12\x13\n\x0fserviceaccounts\x10\x04\x12\n\n\x06owners\x10\x05*U\n\x10PermissionAction\x12\x08\n\x04view\x10\x00\x12\x08\n\x04list\x10\x02\x12\x08\n\x04\x65\x64it\x10\x03\x12\n\n\x06manage\x10\x04\x12\x0b\n\x07service\x10\x05\x12\n\n\x06\x64\x65lete\x10\x06*\x9d\x01\n\x14PermissionObjectType\x12\x17\n\x13unknown_object_type\x10\x00\x12\x13\n\x0f\x63ollection_type\x10\x01\x12\x11\n\rmetadata_type\x10\x02\x12\x18\n\x14system_resource_type\x10\x03\x12\x11\n\rworkflow_type\x10\x04\x12\x17\n\x13workflow_state_type\x10\x05*[\n\x15PermissionSubjectType\x12\x18\n\x14unknown_subject_type\x10\x00\x12\x08\n\x04user\x10\x01\x12\t\n\x05group\x10\x02\x12\x13\n\x0fservice_account\x10\x03\x42%Z#bosca.io/api/protobuf/bosca/contentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosca.content.permissions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#bosca.io/api/protobuf/bosca/content'
  _globals['_PERMISSIONRELATION']._serialized_start=553
  _globals['_PERMISSIONRELATION']._serialized_end=663
  _globals['_PERMISSIONACTION']._serialized_start=665
  _globals['_PERMISSIONACTION']._serialized_end=750
  _globals['_PERMISSIONOBJECTTYPE']._serialized_start=753
  _globals['_PERMISSIONOBJECTTYPE']._serialized_end=910
  _globals['_PERMISSIONSUBJECTTYPE']._serialized_start=912
  _globals['_PERMISSIONSUBJECTTYPE']._serialized_end=1003
  _globals['_PERMISSIONCHECKREQUEST']._serialized_start=51
  _globals['_PERMISSIONCHECKREQUEST']._serialized_end=275
  _globals['_PERMISSIONCHECKRESPONSE']._serialized_start=277
  _globals['_PERMISSIONCHECKRESPONSE']._serialized_end=319
  _globals['_PERMISSIONS']._serialized_start=321
  _globals['_PERMISSIONS']._serialized_end=394
  _globals['_PERMISSION']._serialized_start=397
  _globals['_PERMISSION']._serialized_end=551
# @@protoc_insertion_point(module_scope)
